apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-alts
  name: alts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-alts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-alts
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
        - name: private-alts-container
          image: altsacr.azurecr.io/samples/alts:v3
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.5"
            limits:
              memory: "100Mi"
              cpu: "1"
          ports:
            - containerPort: 8080
          env:
            - name: ALTS_PORT
              value: "8080"
            - name: DATABASE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: connection-string
            - name: DATABASE_MONGODB_DBNAME
              value: cosmodb-alts
            - name: MONGODB_COLLECTION
              value: jobtemplates
      imagePullSecrets:
          - name: acr-secret
